app:
  name: go-crud
  port: 8080

db:
  host: 127.0.0.1:3306
  port: 3306
  name: x_test
  user: root
  password: 123456
  connection_pool:
    max_idle_connection: 10
    max_open_connection: 30
    max_lifetime_connection: 60 #second
    max_idletime_connection: 60 #second
